# Chapter 7: Data wrangling

Questions for Ethan/Josh:
- how do I add, commit and push to github if I want to restructure my repo fx by adding folders for class exercises and readings?


## Dataframes


In [2]:
# dataaaa
age = [17, 19, 21, 37, 18, 19, 47, 18, 19]
score = [12, 10, 11, 15, 16, 14, 25, 21, 29]
rt = [3.552, 1.624, 6.431, 7.132, 2.925, 4.662, 3.634, 3.635, 5.234]
group = ["test", "test", "test", "test", "test", "control", "control", "control", "control"]

# make into dataframe
import pandas as pd

df = pd.DataFrame(
    {'age': age,
     'score': score,
     'rt': rt,
     'group': group
    })
df

age  score     rt    group
0   17     12  3.552     test
1   19     10  1.624     test
2   21     11  6.431     test
3   37     15  7.132     test
4   18     16  2.925     test
5   19     14  4.662  control
6   47     25  3.634  control
7   18     21  3.635  control
8   19     29  5.234  control

In [3]:
# pull out a stored variable
score_data = df['score']
score_data

0    12
1    10
2    11
3    15
4    16
5    14
6    25
7    21
8    29
Name: score, dtype: int64

In [4]:
# only pull out data from 4 first participants
score_data = df['score'][0:4]
score_data

0    12
1    10
2    11
3    15
Name: score, dtype: int64

In [5]:
# extrating data from row instead of column
score_data = df.loc[2] # use the loc attribute of a pandas dataframe
score_data

age         21
score       11
rt       6.431
group     test
Name: 2, dtype: object

In [9]:
# get raw data out of a pandas series
my_row = list(df.loc[2])
my_column = list(df['score'])
print(my_row)
print(my_column)

[np.int64(21), np.int64(11), np.float64(6.431), 'test']
[12, 10, 11, 15, 16, 14, 25, 21, 29]


In [16]:
# smart tips

# see column variables
list(df)

# check how many columns and rows we have
df.shape

# see first data in df
df.head(10) # default is 5, otherwise specify

# see last data in df
df.head(10) # default is 5, otherwise specify

# get all data out of df and into a list
df.values.tolist()

[[17, 12, 3.552, 'test'],
 [19, 10, 1.624, 'test'],
 [21, 11, 6.431, 'test'],
 [37, 15, 7.132, 'test'],
 [18, 16, 2.925, 'test'],
 [19, 14, 4.662, 'control'],
 [47, 25, 3.634, 'control'],
 [18, 21, 3.635, 'control'],
 [19, 29, 5.234, 'control']]

## Tabulating and cross-tabulating data
### cross-tabulation = the construction of frequency tables

In [17]:
# make df
data = {'speaker':["upsy-daisy",  "upsy-daisy",  "upsy-daisy",  "upsy-daisy",  "tombliboo",   "tombliboo",   "makka-pakka", "makka-pakka",
  "makka-pakka", "makka-pakka"],
       'utterance':["pip", "pip", "onk", "onk", "ee",  "oo",  "pip", "pip", "onk", "onk"]}

df = pd.DataFrame(data, columns=['speaker','utterance'])

# cross-tabulate
pd.crosstab(index = df["speaker"], columns = "count")

col_0        count
speaker           
makka-pakka      4
tombliboo        2
upsy-daisy       4

In [18]:
# instead we want to cross-tabulate the speakers with the utterances
pd.crosstab(index=df["speaker"], columns=df["utterance"],margins=True)

utterance    ee  onk  oo  pip  All
speaker                           
makka-pakka   0    2   0    2    4
tombliboo     1    0   1    0    2
upsy-daisy    0    2   0    2    4
All           1    4   1    4   10

In [19]:
# organise in proportions instead of raw counts
tabs = pd.crosstab(index=df["speaker"], columns=df["utterance"],margins=True)

tabs.columns = list(tabs.columns)[0:-1] + ['rowtotals']
tabs.index = list(tabs.index)[0:-1] + ['coltotals']

tabs

ee  onk  oo  pip  rowtotals
makka-pakka   0    2   0    2          4
tombliboo     1    0   1    0          2
upsy-daisy    0    2   0    2          4
coltotals     1    4   1    4         10

In [20]:
# row-wise proportion i.e. which speaker the utterances come from
tabs.div(tabs["rowtotals"], axis=0)

ee  onk   oo  pip  rowtotals
makka-pakka  0.0  0.5  0.0  0.5        1.0
tombliboo    0.5  0.0  0.5  0.0        1.0
upsy-daisy   0.0  0.5  0.0  0.5        1.0
coltotals    0.1  0.4  0.1  0.4        1.0

## Transforming or recoding a variable

In [27]:
# in a survey: On a scale of 1 (strongly disagree) to 7 (strongly agree), to what extent do you agree with the proposition that “Dinosaurs are awesome”?
data = [1, 7, 3, 4, 4, 4, 2, 6, 5, 5]
data

# transform likert scale to be from -3 to +3 instead (makes more sense for the survey)
data = [1, 7, 3, 4, 4, 4, 2, 6, 5, 5]
data = [x-4 for x in data]
data


[-3, 3, -1, 0, 0, 0, -2, 2, 1, 1]

In [28]:
# If your data is in a numpy array rather than a list, it is even easier: just subtract 4 from array
import numpy as np
data2 = np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
data2 = data2 - 4
data2

array([-3,  3, -1,  0,  0,  0, -2,  2,  1,  1])

In [30]:
# take the absolute value of the centred data (i.e. strength)
data = np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
data = data -4
data = abs(data)
data

array([3, 3, 1, 0, 0, 0, 2, 2, 1, 1])

In [31]:
# compute a variable that contains only the direction of the opinion and ignores the strength
data = np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
data = data - 4
data = np.sign(data) # negative is -1, 0 is 0, and positive is 1
data

array([-1,  1, -1,  0,  0,  0, -1,  1,  1,  1])

In [32]:
# collect all this in a dataframe step 1
import pandas as pd
df = pd.DataFrame(
    {'scores': np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
    })

df

scores
0       1
1       7
2       3
3       4
4       4
5       4
6       2
7       6
8       5
9       5

In [33]:
# collect all this in a dataframe step 1
df['centered'] = df['scores']-4
df['opinion_strength'] = abs(df['centered'])
df['opinion_direction'] = np.sign(df['scores']-4)
df

scores  centered  opinion_strength  opinion_direction
0       1        -3                 3                 -1
1       7         3                 3                  1
2       3        -1                 1                 -1
3       4         0                 0                  0
4       4         0                 0                  0
5       4         0                 0                  0
6       2        -2                 2                 -1
7       6         2                 2                  1
8       5         1                 1                  1
9       5         1                 1                  1

In [37]:
# cutting a numeric variable up into discrete categories👇

#age = [60,58,24,26,34,42,31,30,33,2,9]
import pandas as pd
df = pd.DataFrame(
    {'age': np.array([60,58,24,26,34,42,31,30,33,2,9])
    })

df


age
0    60
1    58
2    24
3    26
4    34
5    42
6    31
7    30
8    33
9     2
10    9

In [36]:
# categorize
df['categories'] = pd.cut(x = df['age'], bins = [0,20,40,60], labels = ['young', 'adult', 'older'])
df

age categories
0    60      older
1    58      older
2    24      adult
3    26      adult
4    34      adult
5    42      older
6    31      adult
7    30      adult
8    33      adult
9     2      young
10    9      young

In [38]:
# divide the age variable into three categories of different size, but with approximately identical numbers of people. This could be done by making the breaks correspond to the 0th, 33rd, 66th and 100th percentiles of the data
df['categories'] = pd.qcut(x = df['age'], q = [0, .33, .66, 1] ) # use qcut() function
df

age     categories
0    60   (33.6, 60.0]
1    58   (33.6, 60.0]
2    24  (1.999, 27.2]
3    26  (1.999, 27.2]
4    34   (33.6, 60.0]
5    42   (33.6, 60.0]
6    31   (27.2, 33.6]
7    30   (27.2, 33.6]
8    33   (27.2, 33.6]
9     2  (1.999, 27.2]
10    9  (1.999, 27.2]

## Useful mathematical functions


In [39]:
# python is weird, look:
print(round(4.4))
print(round(4.5)) # WHAT THE HELLZ
print(round(4.51))

# It's not an error, but be aware that python does this

4
4
5


In [45]:
# add a second argument to indicate the number of decimal places desired
a = 3.777298672345782376823578287355
round (a, 5)

b = 4.5553637953
round(b, 2)

4.56

In [49]:
# row-wise means of a dataframe
# df['mean'] = df.mean(axis = 1) # 👺 can't run but this is the code

## Slicing and dicing
